server:
  port: 8080
spring:
  datasource:
    password: 1adnsutelebesi
    url: jdbc:mysql://localhost:3306/bookstore
    username: root
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    enabled: true

  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    password: ngrtheilnrcfzroz
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: newmailfortests1@gmail.com